### ISSUE TITLE
How can I compile this project to a .jar file?

### ISSUE THREAD

**Issue by woolen-sheep** [ForgottenArbiter/SeedSearch#1]
It's a amazing project and I want to add something new to it.
I am a newbee of Java and I tried to build the project with maven. Maven output some class files. I am wondering how I can pack these to a executable jar file?

**Comment by woolen-sheep** [comment]
I've read your pom file and I thought there should be a jar file under the target folder but I get nothing except class files. It may sound stupid, facepalm.

**Comment by ForgottenArbiter** [comment]
Sorry about the kind of weird structure, I was copying what ModTheSpire and BaseMod did.

* Copy desktop-1.0.jar and ModTheSpire.jar from your Slay the Spire folder into `../_lib` relative to the repo.
* Run `mvn package`

This will package the jar and copy the jar from target to `../_ModTheSpire/mods`, but if you have your modded setup somewhere else, you should copy it manually to where it needs to go.

**Comment by woolen-sheep** [comment]
Thanks a lot!
